services:
  db:
    image: postgres
    container_name: alert-bot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alert-bot-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
